name: Run Rest assured test cases
on:
  push:["master"]


jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: "18"
          cache: maven
      - run: mvn clean test